### ISSUE TITLE
Incompatible with MoreCulling

### ISSUE THREAD

**Issue by xpopy** [Viotomix/ItemFrameTweaks#1]
When using https://github.com/fxmorin/moreculling the items in invisible item frames are still offset

![image](https://github.com/Viotomix/ItemFrameTweaks/assets/3540971/7b36a883-6572-4dac-b4aa-b032e707fb5f)

**Comment by Viotomix** [comment]
I'll try and have a look into if I can fix this, once I have time. Thanks for the report!

**Comment by Viotomix** [comment]
Ok, after way too long I've finally had a chance to look at the code and unfortunately More culling just overwrites the original method as a whole. To my understanding that means I cannot make our mods compatible with one another unless the author changes their code.

**Comment by Lucipo** [comment]
you can disable more culling's item frame changes in their config to fix
