### ISSUE TITLE
Request for a 1.21 port

### ISSUE THREAD

**Issue by SilentZK** [Viotomix/ItemFrameTweaks#2]
Hey, I really enjoy your mod, which fixes my issues with item frames. I was wondering if a **1.21** port would be possible.

**Comment by Viotomix** [comment]
Little bit of a late response, but yes. I'll look into porting it through the newer versions, hopefully with little problems.

I forget I even made this mod sometimes so I appreciate the reminder 😅

**Comment by Viotomix** [comment]
Updated through all version from 1.20.1 to 1.21

**Comment by SilentZK** [comment]
I'm having an issue with the loading screen when I'm using your mod. I've created an instance using only the Item Frame Tweaks mod and Fabric API. Once I start Minecraft, it boots up normally, but the progress bar gets stuck throughout the process. 

The only fix I have for this issue is using the Remove Reloading Screen mod, but it's incompatible with some of the mods I'd like to use.

![image](https://github.com/user-attachments/assets/79a4a46d-392d-4790-9edc-aed956fd2cbc)

**Comment by Viotomix** [comment]
I'll have a look at it as soon as I can. This is still on 1.21 correct?

**Comment by SilentZK** [comment]
Yes, 1.21

**Comment by Viotomix** [comment]
Should be fixed in the latest version, let me know if it doesn't work again

**Comment by SilentZK** [comment]
Works flawlessly so far. Thanks a lot!
